### ISSUE TITLE
Question: What is up with `0 + Intercept`?

### ISSUE THREAD

**Issue by malcolmbarrett** [ASKurz/Working-through-Regression-and-other-stories#1]
Thanks for yet another brms-y resource!

❓: This model uses `0 + Intercept`, but I can't figure out what that means or any documentation for that type of syntax. What's up with this one? https://github.com/ASKurz/Working-through-Regression-and-other-stories/blob/63bcb01a8f62c4b0c004909b4fe8c22ff20fc914/01.Rmd#L64-L70

**Comment by ASKurz** [comment]
Good question. Check out the **Parameterization of the population-level intercept** subsection of the brms reference manual (https://cran.r-project.org/web/packages/brms/brms.pdf). In short, when you set your priors `brms::brm()` assumes your predictors are all centered, which effects the way the prior on the default intercept is set internally. When your predictors are not mean centered, you can avoid this default behavior by removing the default intercept (`0`) and replacing it with the special term `Intercept`. Then when you set the priors, the new `Intercept` parameter will not presume the predictors are centered. When you use the default weak priors, this generally isn't an issue. But, IMO, it's a good idea to get into the practice of using the `0 + Intercept` syntax so that it comes naturally when you're analyzing real data with real priors.

**Comment by ASKurz** [comment]
Do you mind if I share this question in a tweet? It's an important one which I suspect many people overlook.

**Comment by malcolmbarrett** [comment]
Yes, please do! Thanks for the answer 🙏

**Comment by Crismoc** [comment]
A follow-up on this, why in this case the `0 + Intercept` is preferable to the default? When comparing the original textbook results I get more similar results with the default in brms (I only tried it 4 times, but it doesn't seem to be due to a particular model sampling)

```r
hibbs <- read.table("hibbs.dat", header=TRUE)
library(rstanarm)
M1 <- stan_glm(vote ~ growth, data=hibbs)

library(brms)
M1b <- brm(vote ~ growth, data = hibbs)
M1c <- brm(vote ~ 0 + Intercept + growth, data = hibbs)

# Compare results
M1$stan_summary
summary(M1b)$fixed
summary(M1c)$fixed
```

BTW, thanks for doing this work @ASKurz!

**Comment by ASKurz** [comment]
To rigorously answer that question, one would have to inspect the relevant default settings for `brms::brm()` and `rstanarm::stan_glm()`. The issue with the `0 + Intercept` aside, I'm pretty sure the two packages use different default priors. So regardless, neither of your `brm()` models are technically identical with the `stan_glm()` model. Further, keep in mind that there are only 16 cases in the data, which will make the models quite sensitive to both the priors and to MCMC sampling error.
